import assert from "node:assert/strict";
import { createHmac } from "node:crypto";
import test from "node:test";

import {
  SignedProxyBoundaryNotConfiguredError,
  SignedProxyRejectedError,
} from "./boundaries.js";
import type { StagingWorkerEnv } from "./contracts.js";
import { WebCryptoShopifyAppProxyVerifier } from "./webcrypto-app-proxy.js";

const SECRET = "unit-test-staging-app-proxy-secret";
const SHOP = "base-note-subscription-staging.myshopify.com";
const NOW = 1_800_000_000;
const TARGET = "https://basenote-profile-queue-staging.wilson-af8.workers.dev/api/shopify/app-proxy/profile-queue";

test("Web Crypto verifier accepts a fresh Shopify-signed request for the exact staging shop", async () => {
  const verifier = new WebCryptoShopifyAppProxyVerifier({ nowSeconds: () => NOW });
  const identity = await verifier.verify({
    environment: configuredEnvironment(),
    request: signedRequest(),
  });

  assert.deepEqual(identity, {
    shopDomain: SHOP,
    shopifyCustomerId: "101",
    storefrontPathPrefix: "/apps/basenote-staging",
  });
});

test("Web Crypto verifier matches a fixed duplicate-parameter HMAC vector", async () => {
  // This signature is intentionally hard-coded, not generated by the test's
  // canonicalizer. It covers Shopify's documented duplicate grouping,
  // comma-joining, sort, and concatenation convention.
  const secret = "unit-test-app-proxy-vector-secret";
  const query = "extra=z&extra=a&logged_in_customer_id=101&path_prefix=%2Fapps%2Fbasenote-staging&shop=base-note-subscription-staging.myshopify.com&timestamp=1800000000&signature=53c6254df72a77c3807cf93ef9f0a19d1c4c62623dbfbfebf5b39f117bbb0329";
  const verifier = new WebCryptoShopifyAppProxyVerifier({ nowSeconds: () => 1_800_000_000 });
  const identity = await verifier.verify({
    environment: {
      BASENOTE_RUNTIME_STAGE: "staging",
      SHOPIFY_APP_PROXY_SHARED_SECRET: secret,
      STAGING_SHOP_DOMAIN: SHOP,
    },
    request: new Request(`${TARGET}?${query}`),
  });
  assert.equal(identity.storefrontPathPrefix, "/apps/basenote-staging");
});

test("Web Crypto verifier rejects a signature tamper, wrong staging shop, and anonymous proxy request", async () => {
  const verifier = new WebCryptoShopifyAppProxyVerifier({ nowSeconds: () => NOW });
  const tampered = new Request(signedRequest().url.replace("logged_in_customer_id=101", "logged_in_customer_id=102"));
  await assert.rejects(
    verifier.verify({ environment: configuredEnvironment(), request: tampered }),
    SignedProxyRejectedError,
  );

  await assert.rejects(
    verifier.verify({
      environment: configuredEnvironment(),
      request: signedRequest({ shop: "another-staging-shop.myshopify.com" }),
    }),
    SignedProxyRejectedError,
  );

  await assert.rejects(
    verifier.verify({
      environment: configuredEnvironment(),
      request: signedRequest({ logged_in_customer_id: "" }),
    }),
    SignedProxyRejectedError,
  );
});

test("Web Crypto verifier fails closed without runtime-only secret or exact staging shop", async () => {
  const verifier = new WebCryptoShopifyAppProxyVerifier({ nowSeconds: () => NOW });
  await assert.rejects(
    verifier.verify({
      environment: { ...configuredEnvironment(), SHOPIFY_APP_PROXY_SHARED_SECRET: undefined },
      request: signedRequest(),
    }),
    SignedProxyBoundaryNotConfiguredError,
  );
  await assert.rejects(
    verifier.verify({
      environment: { ...configuredEnvironment(), STAGING_SHOP_DOMAIN: "REPLACE_WITH_STAGING_SHOP.myshopify.com" },
      request: signedRequest(),
    }),
    SignedProxyBoundaryNotConfiguredError,
  );
});

test("Web Crypto verifier rejects HMAC-bearing HTTP and an explicitly insecure forwarded protocol", async () => {
  const verifier = new WebCryptoShopifyAppProxyVerifier({ nowSeconds: () => NOW });
  const secureUrl = signedRequest().url;
  const insecureUrl = secureUrl.replace(/^https:/, "http:");

  await assert.rejects(
    verifier.verify({ environment: configuredEnvironment(), request: new Request(insecureUrl) }),
    SignedProxyRejectedError,
  );
  await assert.rejects(
    verifier.verify({
      environment: configuredEnvironment(),
      request: new Request(secureUrl, { headers: { "X-Forwarded-Proto": "http" } }),
    }),
    SignedProxyRejectedError,
  );
});

function configuredEnvironment(): StagingWorkerEnv {
  return {
    BASENOTE_RUNTIME_STAGE: "staging",
    SHOPIFY_APP_PROXY_SHARED_SECRET: SECRET,
    STAGING_SHOP_DOMAIN: SHOP,
  };
}

function signedRequest(overrides: Record<string, string> = {}): Request {
  const values = {
    extra: "one",
    logged_in_customer_id: "101",
    path_prefix: "%2Fapps%2Fbasenote-staging",
    shop: SHOP,
    timestamp: String(NOW),
    ...overrides,
  };
  const unsigned = Object.entries(values)
    .map(([key, value]) => `${key}=${value}`)
    .join("&");
  return new Request(`${TARGET}?${unsigned}&signature=${sign(unsigned)}`);
}

function sign(unsignedQuery: string): string {
  return createHmac("sha256", SECRET).update(canonicalize(unsignedQuery), "utf8").digest("hex");
}

function canonicalize(rawQuery: string): string {
  const grouped = new Map<string, string[]>();
  for (const segment of rawQuery.split("&")) {
    const separator = segment.indexOf("=");
    const rawKey = separator === -1 ? segment : segment.slice(0, separator);
    const rawValue = separator === -1 ? "" : segment.slice(separator + 1);
    const key = decodeURIComponent(rawKey.replace(/\+/g, " "));
    const value = decodeURIComponent(rawValue.replace(/\+/g, " "));
    const values = grouped.get(key);
    if (values) values.push(value);
    else grouped.set(key, [value]);
  }
  return [...grouped.entries()]
    .map(([key, values]) => `${key}=${values.join(",")}`)
    .sort()
    .join("");
}
