import {
  asProductVariantId,
  type ProductVariantId,
} from "../domain/ids.js";
import {
  asBindingId,
  asCycleKey,
  asIsoTimestamp,
  asMerchantTimezone,
  asShipMonth,
  type BindingId,
  type CycleKey,
  type IsoTimestamp,
  type QueueSlotState,
  type ShipMonth,
} from "../queue/types.js";

/**
 * A future shipment always contains its automatic FOTM base selection. These
 * are the separately-priced customer add-ons, not a replacement for FOTM.
 */
export const MAX_FUTURE_ADD_ONS_PER_CYCLE = 4 as const;
export const FUTURE_ADD_ON_UNIT_PRICE_CENTS = 1_800 as const;

export type ProfileQueueAddOnId = string & { readonly __brand: "ProfileQueueAddOnId" };
export type ProfileQueueMutationId = string & { readonly __brand: "ProfileQueueMutationId" };
export type ProfileQueueIdempotencyKey = string & { readonly __brand: "ProfileQueueIdempotencyKey" };
export type ProfileQueueActorRef = string & { readonly __brand: "ProfileQueueActorRef" };

export type ProfileQueueFotmStatus = "UNPUBLISHED" | "PUBLISHED" | "RESOLVED";

/** The merchant-controlled automatic base item for a delivery cycle. */
export interface ProfileQueueFotm {
  readonly cutoffAt: IsoTimestamp | null;
  readonly merchantTimezone: string | null;
  readonly status: ProfileQueueFotmStatus;
  readonly variantId: ProductVariantId | null;
}

/** A customer-selected, $18.00 additional vial for exactly one future cycle. */
export interface ProfileQueueAddOn {
  readonly createdAt: IsoTimestamp;
  readonly id: ProfileQueueAddOnId;
  readonly position: number;
  readonly unitPriceCents: typeof FUTURE_ADD_ON_UNIT_PRICE_CENTS;
  readonly updatedAt: IsoTimestamp;
  readonly variantId: ProductVariantId;
}

/**
 * The customer-facing queue aggregate. `bindingId` is server-side scope from
 * an authenticated session; it must never be trusted from a browser request.
 */
export interface ProfileQueueCycle {
  readonly addOns: readonly ProfileQueueAddOn[];
  readonly bindingId: BindingId;
  readonly cycleKey: CycleKey;
  readonly fotm: ProfileQueueFotm;
  readonly revision: number;
  readonly shipMonth: ShipMonth;
  readonly state: QueueSlotState;
  readonly updatedAt: IsoTimestamp;
}

export type ProfileQueueCustomerMutation =
  | {
      readonly kind: "ADD_ADD_ON";
      /** Generated by the server from an authenticated, idempotent request. */
      readonly addOnId: string;
      readonly variantId: string;
    }
  | {
      readonly kind: "CHANGE_ADD_ON";
      readonly addOnId: string;
      readonly variantId: string;
    }
  | {
      readonly kind: "REMOVE_ADD_ON";
      readonly addOnId: string;
    };

/**
 * Browser/API contract. The authenticated route supplies `bindingId` from its
 * session context; callers cannot select another customer's contract here.
 */
export interface ProfileQueueApiRequest {
  readonly cycleKey: string;
  readonly expectedRevision: number;
  readonly idempotencyKey: string;
  readonly mutation: ProfileQueueCustomerMutation;
  readonly shipMonth: string;
}

export type NormalizedProfileQueueCustomerMutation =
  | {
      readonly kind: "ADD_ADD_ON";
      readonly addOnId: ProfileQueueAddOnId;
      readonly variantId: ProductVariantId;
    }
  | {
      readonly kind: "CHANGE_ADD_ON";
      readonly addOnId: ProfileQueueAddOnId;
      readonly variantId: ProductVariantId;
    }
  | {
      readonly kind: "REMOVE_ADD_ON";
      readonly addOnId: ProfileQueueAddOnId;
    };

/** Parsed server boundary for the browser/API request shape above. */
export interface NormalizedProfileQueueApiRequest {
  readonly cycleKey: CycleKey;
  readonly expectedRevision: number;
  readonly idempotencyKey: ProfileQueueIdempotencyKey;
  readonly mutation: NormalizedProfileQueueCustomerMutation;
  readonly shipMonth: ShipMonth;
}

export interface AuthenticatedProfileQueueRouteContext {
  readonly actorRef: string;
  readonly bindingId: string;
}

export interface ProfileQueueMutationAuditRecord {
  readonly actorRef: ProfileQueueActorRef;
  readonly bindingId: BindingId;
  readonly cycleKey: CycleKey;
  readonly expectedRevision: number | null;
  readonly idempotencyKey: ProfileQueueIdempotencyKey;
  readonly mutationId: ProfileQueueMutationId;
  readonly mutationKind:
    | "CREATE_CYCLE"
    | ProfileQueueCustomerMutation["kind"]
    | "PUBLISH_FOTM"
    | "RESOLVE_FOTM";
  readonly occurredAt: IsoTimestamp;
  readonly resultingRevision: number;
}

const ADD_ON_ID = /^pqa_[A-Za-z0-9][A-Za-z0-9._:-]{7,127}$/;
const MUTATION_ID = /^pqm_[A-Za-z0-9][A-Za-z0-9._:-]{7,127}$/;
const IDEMPOTENCY_KEY = /^pqk_[A-Za-z0-9][A-Za-z0-9._:-]{7,191}$/;
const ACTOR_REF = /^[A-Za-z0-9][A-Za-z0-9._:-]{2,127}$/;

export function asProfileQueueAddOnId(value: string): ProfileQueueAddOnId {
  if (!ADD_ON_ID.test(value)) {
    throw new Error("addOnId must begin with pqa_ and contain 12-132 URL-safe characters.");
  }
  return value as ProfileQueueAddOnId;
}

export function asProfileQueueMutationId(value: string): ProfileQueueMutationId {
  if (!MUTATION_ID.test(value)) {
    throw new Error("mutationId must begin with pqm_ and contain 12-132 URL-safe characters.");
  }
  return value as ProfileQueueMutationId;
}

export function asProfileQueueIdempotencyKey(value: string): ProfileQueueIdempotencyKey {
  if (!IDEMPOTENCY_KEY.test(value)) {
    throw new Error("idempotencyKey must begin with pqk_ and contain 12-196 URL-safe characters.");
  }
  return value as ProfileQueueIdempotencyKey;
}

export function asProfileQueueActorRef(value: string): ProfileQueueActorRef {
  if (!ACTOR_REF.test(value)) {
    throw new Error("actorRef must be a 3-128 character opaque identifier, never an email address.");
  }
  return value as ProfileQueueActorRef;
}

/**
 * Parses untrusted request data while structurally rejecting a browser-supplied
 * binding ID. The route must attach its binding from verified server context.
 */
export function parseProfileQueueApiRequest(value: unknown): NormalizedProfileQueueApiRequest {
  const record = asRecord(value, "Profile queue request must be an object.");
  if (Object.hasOwn(record, "bindingId")) {
    throw new Error("A profile queue request must not supply a contract binding ID.");
  }
  const mutation = asRecord(record.mutation, "Profile queue mutation must be an object.");
  return {
    cycleKey: asCycleKey(readString(record, "cycleKey")),
    expectedRevision: readRevision(record.expectedRevision),
    idempotencyKey: asProfileQueueIdempotencyKey(readString(record, "idempotencyKey")),
    mutation: parseCustomerMutation(mutation),
    shipMonth: asShipMonth(readString(record, "shipMonth")),
  };
}

/** Validates the authenticated route context assembled by server middleware. */
export function normalizeAuthenticatedProfileQueueRouteContext(
  value: AuthenticatedProfileQueueRouteContext,
): { readonly actorRef: ProfileQueueActorRef; readonly bindingId: BindingId } {
  return {
    actorRef: asProfileQueueActorRef(value.actorRef),
    bindingId: asBindingId(value.bindingId),
  };
}

export function assertProfileQueueRevision(value: number): void {
  if (!Number.isSafeInteger(value) || value < 0) {
    throw new Error("expectedRevision must be a non-negative safe integer.");
  }
}

export function createEmptyProfileQueueCycle(input: {
  readonly bindingId: string;
  readonly cycleKey: string;
  readonly shipMonth: string;
  readonly updatedAt: string;
}): ProfileQueueCycle {
  return {
    addOns: [],
    bindingId: asBindingId(input.bindingId),
    cycleKey: asCycleKey(input.cycleKey),
    fotm: {
      cutoffAt: null,
      merchantTimezone: null,
      status: "UNPUBLISHED",
      variantId: null,
    },
    revision: 0,
    shipMonth: asShipMonth(input.shipMonth),
    state: "OPEN",
    updatedAt: asIsoTimestamp(input.updatedAt),
  };
}

/** Validates both the durable aggregate and its customer-priced add-on rule. */
export function assertProfileQueueCycleInvariant(cycle: ProfileQueueCycle): void {
  asBindingId(cycle.bindingId);
  asCycleKey(cycle.cycleKey);
  asShipMonth(cycle.shipMonth);
  asIsoTimestamp(cycle.updatedAt);
  assertProfileQueueRevision(cycle.revision);

  if (cycle.addOns.length > MAX_FUTURE_ADD_ONS_PER_CYCLE) {
    throw new Error(`A future shipment may have at most ${MAX_FUTURE_ADD_ONS_PER_CYCLE} $18 add-ons.`);
  }

  const ids = new Set<ProfileQueueAddOnId>();
  const positions = new Set<number>();
  for (const [index, addOn] of cycle.addOns.entries()) {
    asProfileQueueAddOnId(addOn.id);
    asProductVariantId(addOn.variantId);
    asIsoTimestamp(addOn.createdAt);
    asIsoTimestamp(addOn.updatedAt);
    if (addOn.unitPriceCents !== FUTURE_ADD_ON_UNIT_PRICE_CENTS) {
      throw new Error("Future queue add-ons must retain the exact $18.00 unit price.");
    }
    if (!Number.isSafeInteger(addOn.position) || addOn.position !== index + 1) {
      throw new Error("Future queue add-ons must use contiguous positions beginning at one.");
    }
    if (addOn.position > MAX_FUTURE_ADD_ONS_PER_CYCLE || positions.has(addOn.position)) {
      throw new Error("Future queue add-on positions must be unique and within the four-item limit.");
    }
    if (ids.has(addOn.id)) throw new Error("A future queue add-on ID may appear only once per cycle.");
    ids.add(addOn.id);
    positions.add(addOn.position);
  }

  assertFotmInvariant(cycle.fotm);
}

function assertFotmInvariant(fotm: ProfileQueueFotm): void {
  if (fotm.status === "UNPUBLISHED") {
    if (fotm.variantId !== null || fotm.cutoffAt !== null || fotm.merchantTimezone !== null) {
      throw new Error("An unpublished FOTM must not contain a variant, cutoff, or timezone.");
    }
    return;
  }

  if (fotm.variantId === null || fotm.cutoffAt === null || fotm.merchantTimezone === null) {
    throw new Error("A published or resolved FOTM requires an exact variant, cutoff, and merchant timezone.");
  }
  asProductVariantId(fotm.variantId);
  asIsoTimestamp(fotm.cutoffAt);
  asMerchantTimezone(fotm.merchantTimezone);
}

function parseCustomerMutation(record: Record<string, unknown>): NormalizedProfileQueueCustomerMutation {
  const kind = readString(record, "kind");
  switch (kind) {
    case "ADD_ADD_ON":
      return {
        addOnId: asProfileQueueAddOnId(readString(record, "addOnId")),
        kind,
        variantId: asProductVariantId(readString(record, "variantId")),
      };
    case "CHANGE_ADD_ON":
      return {
        addOnId: asProfileQueueAddOnId(readString(record, "addOnId")),
        kind,
        variantId: asProductVariantId(readString(record, "variantId")),
      };
    case "REMOVE_ADD_ON":
      return { addOnId: asProfileQueueAddOnId(readString(record, "addOnId")), kind };
    default:
      throw new Error("Profile queue mutation kind is unsupported.");
  }
}

function asRecord(value: unknown, message: string): Record<string, unknown> {
  if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error(message);
  return value as Record<string, unknown>;
}

function readString(record: Record<string, unknown>, key: string): string {
  const value = record[key];
  if (typeof value !== "string") throw new Error(`${key} must be a string.`);
  return value;
}

function readRevision(value: unknown): number {
  if (typeof value !== "number") throw new Error("expectedRevision must be a number.");
  assertProfileQueueRevision(value);
  return value;
}
