#!/usr/bin/env python3
"""Frame every fragrance's grid photo the same way (Jeff, 2026-09-11: "anyway to resize all the images quickly").

For each product it downloads the featured image from the storefront, flattens transparent PNGs onto white, trims to the
bottle, optionally removes a non-white studio background with fal.ai (--rembg), and re-frames the bottle on a 600x600
white canvas at 80% of the height. It writes <media>/img/grid/<handle>.jpg plus manifest.json, then regenerates
snippets/grid-photo.liquid. The theme uses a framed photo only while the product still shows the image it was made
from, so a new photo uploaded in Shopify takes over on its own until this script is re-run.

Usage (Pillow required; /opt/anaconda3/bin/python3 has it):
  python3 scripts/normalize_grid_photos.py --media <content-worktree>/worker/media/public \
      [--only handle1,handle2] [--rembg handle3,handle4] [--snippet snippets/grid-photo.liquid]
Then deploy the media worker (npx -y wrangler@3 deploy in worker/media) and push snippets/grid-photo.liquid.
"""
import argparse
import io
import json
import os
import re
import urllib.request

from PIL import Image, ImageChops

STORE = 'https://basenotescent.com'
MEDIA_URL = 'https://basenote-media.wilson-af8.workers.dev/img/grid/'
SIZE, FILL_H, FILL_W = 600, 0.80, 0.74


def fal_key():
    key = os.environ.get('FAL_KEY')
    env = '/Users/wilsonwu/Desktop/basenote/.env'
    if not key and os.path.exists(env):
        for line in open(env):
            m = re.match(r'^(FAL_KEY|FAL_API_KEY2)=(.*)$', line.strip())
            if m:
                key = m.group(2).strip('"\'')
    return key


def remove_background(url):
    for model in ('fal-ai/birefnet', 'fal-ai/imageutils/rembg'):
        try:
            req = urllib.request.Request(f'https://fal.run/{model}', data=json.dumps({'image_url': url}).encode(),
                                         headers={'Authorization': f'Key {fal_key()}', 'Content-Type': 'application/json'})
            out = json.load(urllib.request.urlopen(req, timeout=120))
            return Image.open(io.BytesIO(urllib.request.urlopen(out['image']['url'], timeout=60).read()))
        except Exception as exc:  # fall through to the next model, then to a plain trim
            print(f'  background removal via {model} failed: {exc}')
    return None


def frame(im):
    if im.mode in ('RGBA', 'LA', 'P'):
        im = im.convert('RGBA')
        flat = Image.new('RGB', im.size, (255, 255, 255))
        flat.paste(im, mask=im.split()[-1])
        im, bg = flat, (255, 255, 255)
    else:
        im = im.convert('RGB')
        bg = im.getpixel((3, 3))
    box = ImageChops.difference(im, Image.new('RGB', im.size, bg)).convert('L').point(lambda v: 255 if v > 40 else 0).getbbox()
    box = box or (0, 0) + im.size
    box = (max(0, box[0] - 6), max(0, box[1] - 6), min(im.width, box[2] + 6), min(im.height, box[3] + 6))
    crop = im.crop(box)
    scale = min(SIZE * FILL_H / crop.height, SIZE * FILL_W / crop.width)
    crop = crop.resize((max(1, int(crop.width * scale)), max(1, int(crop.height * scale))), Image.LANCZOS)
    canvas = Image.new('RGB', (SIZE, SIZE), (255, 255, 255))
    canvas.paste(crop, ((SIZE - crop.width) // 2, (SIZE - crop.height) // 2))
    return canvas


def write_snippet(manifest, path):
    lines = ['{% doc %}',
             '  Uniformly framed grid photo for a fragrance (Jeff 2026-09-11: "resize all the images").',
             '  Echoes the photo URL only while the product still shows the image it was made from;',
             '  once someone changes the product photo in Shopify, this echoes nothing and the card uses the new photo.',
             '  Generated by scripts/normalize_grid_photos.py; do not edit by hand.',
             '',
             '  @param {string} handle - Product handle.',
             '  @param {number} image_id - ID of the image the card would otherwise show.',
             '{% enddoc %}', '{%- liquid', '  case handle']
    for handle in sorted(manifest):
        entry = manifest[handle]
        lines += [f"    when '{handle}'", f"      if image_id == {entry['src_image_id']}",
                  f"        echo '{MEDIA_URL}{handle}.jpg?v={entry['version']}'", '      endif']
    lines += ['  endcase', '-%}']
    open(path, 'w').write('\n'.join(lines) + '\n')


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--media', required=True, help='worker/media/public directory of the media worker')
    ap.add_argument('--only', default='', help='comma-separated handles to (re)process; default all')
    ap.add_argument('--rembg', default='', help='comma-separated handles that need background removal')
    ap.add_argument('--snippet', default='snippets/grid-photo.liquid')
    args = ap.parse_args()
    out_dir = os.path.join(args.media, 'img', 'grid')
    os.makedirs(out_dir, exist_ok=True)
    manifest_path = os.path.join(out_dir, 'manifest.json')
    manifest = json.load(open(manifest_path)) if os.path.exists(manifest_path) else {}
    only = {h for h in args.only.split(',') if h}
    rembg = {h for h in args.rembg.split(',') if h}
    products = json.load(urllib.request.urlopen(f'{STORE}/products.json?limit=250', timeout=60))['products']
    for p in products:
        handle = p['handle']
        if handle == 'extra-5ml-vial-add-on' or not p.get('images') or (only and handle not in only):
            continue
        image = p['images'][0]
        url = image['src'] + ('&' if '?' in image['src'] else '?') + 'width=1200'
        src = remove_background(url) if handle in rembg else None
        if src is None:
            src = Image.open(io.BytesIO(urllib.request.urlopen(url, timeout=60).read()))
        frame(src).save(os.path.join(out_dir, f'{handle}.jpg'), quality=86, optimize=True)
        previous = manifest.get(handle, {})
        manifest[handle] = {'src_image_id': image['id'], 'version': previous.get('version', 0) + 1}
        print(f'framed {handle}')
    json.dump(manifest, open(manifest_path, 'w'), indent=1)
    write_snippet(manifest, args.snippet)
    print(f'{len(manifest)} photos in {out_dir}; snippet written to {args.snippet}')


if __name__ == '__main__':
    main()
